### ISSUE TITLE
bug 重复存元素

### ISSUE THREAD

**Issue by differentzhang** [dclemon/PU_eventkill#2]
您设置了数组存未开始任务，是10分钟检查一次，如果代码在活动开始前50分钟就运行此代码，就会往数组中每10分钟添加一次相同的任务。会在数组中出现好几次相同的任务，所以应该在下一次添加任务前，clear一次数组，保证数组的元素不重复。

**Comment by dclemon** [comment]
已修复：
if t < int(re['startline']) and re not in submit_list:
